# Generated by cucumber-sinatra. (Mon Oct 25 21:26:17 -0600 2010)

ENV['RACK_ENV'] = 'test'

app_file = File.join(File.dirname(__FILE__), '..', '..', 'app.rb') 
require app_file
Sinatra::Application.app_file = app_file

begin require 'rspec/expectations'; rescue LoadError; require 'spec/expectations'; end

require 'rack/test'
require 'capybara/cucumber'

Capybara.app = Sinatra::Application

db = CouchRest.database!("http://127.0.0.1:5984/" << ENV['DB_NAME'])

Before do
    db.recreate!
    user = User.new({:username => 'user', :password => Digest::MD5.hexdigest('test'), :email => 'someone@whatever.com'})
    user.save
end
